# coding: utf-8

"""
    fave

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0-prealpha
    Contact: sabyasachi@datafund.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AddDocumentsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'documents': 'list[Document]',
        'name': 'str',
        'properties_to_vectorize': 'list[str]'
    }

    attribute_map = {
        'documents': 'documents',
        'name': 'name',
        'properties_to_vectorize': 'propertiesToVectorize'
    }

    def __init__(self, documents=None, name=None, properties_to_vectorize=None):  # noqa: E501
        """AddDocumentsRequest - a model defined in Swagger"""  # noqa: E501
        self._documents = None
        self._name = None
        self._properties_to_vectorize = None
        self.discriminator = None
        if documents is not None:
            self.documents = documents
        if name is not None:
            self.name = name
        if properties_to_vectorize is not None:
            self.properties_to_vectorize = properties_to_vectorize

    @property
    def documents(self):
        """Gets the documents of this AddDocumentsRequest.  # noqa: E501

        The actual list of Objects.  # noqa: E501

        :return: The documents of this AddDocumentsRequest.  # noqa: E501
        :rtype: list[Document]
        """
        return self._documents

    @documents.setter
    def documents(self, documents):
        """Sets the documents of this AddDocumentsRequest.

        The actual list of Objects.  # noqa: E501

        :param documents: The documents of this AddDocumentsRequest.  # noqa: E501
        :type: list[Document]
        """

        self._documents = documents

    @property
    def name(self):
        """Gets the name of this AddDocumentsRequest.  # noqa: E501

        Name of the collection  # noqa: E501

        :return: The name of this AddDocumentsRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AddDocumentsRequest.

        Name of the collection  # noqa: E501

        :param name: The name of this AddDocumentsRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def properties_to_vectorize(self):
        """Gets the properties_to_vectorize of this AddDocumentsRequest.  # noqa: E501

        Array of property names to be vectorized.  # noqa: E501

        :return: The properties_to_vectorize of this AddDocumentsRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._properties_to_vectorize

    @properties_to_vectorize.setter
    def properties_to_vectorize(self, properties_to_vectorize):
        """Sets the properties_to_vectorize of this AddDocumentsRequest.

        Array of property names to be vectorized.  # noqa: E501

        :param properties_to_vectorize: The properties_to_vectorize of this AddDocumentsRequest.  # noqa: E501
        :type: list[str]
        """

        self._properties_to_vectorize = properties_to_vectorize

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddDocumentsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddDocumentsRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
