# coding: utf-8

"""
    fave

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0-prealpha
    Contact: sabyasachi@datafund.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NearestDocumentsByVectorRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vector': 'list[float]',
        'name': 'str',
        'distance': 'float',
        'limit': 'float'
    }

    attribute_map = {
        'vector': 'vector',
        'name': 'name',
        'distance': 'distance',
        'limit': 'limit'
    }

    def __init__(self, vector=None, name=None, distance=None, limit=None):  # noqa: E501
        """NearestDocumentsByVectorRequest - a model defined in Swagger"""  # noqa: E501
        self._vector = None
        self._name = None
        self._distance = None
        self._limit = None
        self.discriminator = None
        if vector is not None:
            self.vector = vector
        if name is not None:
            self.name = name
        if distance is not None:
            self.distance = distance
        if limit is not None:
            self.limit = limit

    @property
    def vector(self):
        """Gets the vector of this NearestDocumentsByVectorRequest.  # noqa: E501

        The vector to search for  # noqa: E501

        :return: The vector of this NearestDocumentsByVectorRequest.  # noqa: E501
        :rtype: list[float]
        """
        return self._vector

    @vector.setter
    def vector(self, vector):
        """Sets the vector of this NearestDocumentsByVectorRequest.

        The vector to search for  # noqa: E501

        :param vector: The vector of this NearestDocumentsByVectorRequest.  # noqa: E501
        :type: list[float]
        """

        self._vector = vector

    @property
    def name(self):
        """Gets the name of this NearestDocumentsByVectorRequest.  # noqa: E501

        Name of the collection  # noqa: E501

        :return: The name of this NearestDocumentsByVectorRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NearestDocumentsByVectorRequest.

        Name of the collection  # noqa: E501

        :param name: The name of this NearestDocumentsByVectorRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def distance(self):
        """Gets the distance of this NearestDocumentsByVectorRequest.  # noqa: E501


        :return: The distance of this NearestDocumentsByVectorRequest.  # noqa: E501
        :rtype: float
        """
        return self._distance

    @distance.setter
    def distance(self, distance):
        """Sets the distance of this NearestDocumentsByVectorRequest.


        :param distance: The distance of this NearestDocumentsByVectorRequest.  # noqa: E501
        :type: float
        """

        self._distance = distance

    @property
    def limit(self):
        """Gets the limit of this NearestDocumentsByVectorRequest.  # noqa: E501


        :return: The limit of this NearestDocumentsByVectorRequest.  # noqa: E501
        :rtype: float
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this NearestDocumentsByVectorRequest.


        :param limit: The limit of this NearestDocumentsByVectorRequest.  # noqa: E501
        :type: float
        """

        self._limit = limit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NearestDocumentsByVectorRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NearestDocumentsByVectorRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
