# coding: utf-8

# flake8: noqa

"""
    fave

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0-prealpha
    Contact: sabyasachi@datafund.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from fave_api.api.default_api import DefaultApi
# import ApiClient
from fave_api.api_client import ApiClient
from fave_api.configuration import Configuration
# import models into sdk package
from fave_api.models.add_documents_request import AddDocumentsRequest
from fave_api.models.collection import Collection
from fave_api.models.document import Document
from fave_api.models.error_response import ErrorResponse
from fave_api.models.error_response_error import ErrorResponseError
from fave_api.models.index import Index
from fave_api.models.model_property import ModelProperty
from fave_api.models.nearest_documents_by_vector_request import NearestDocumentsByVectorRequest
from fave_api.models.nearest_documents_request import NearestDocumentsRequest
from fave_api.models.nearest_documents_response import NearestDocumentsResponse
from fave_api.models.ok_response import OKResponse
